title: Hack Night
permalink: /:year/:month/:day/:title/
paginate: 5

email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_handle: uncoded
github_org:  uncodedlb


markdown: kramdown
highlighter: rouge

theme: jekyll-theme-minimal

exclude:
  - README.markdown
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CODE_OF_CONDUCT.md
  - tmp
  - vendor
  - .gitignore
  - .git
  - .c9
  - foo
